---
title: "Assignment 1: Introduction"
author: "Shivani Kuckreja"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have no formal experience with data analytics, R, and Git. The most similar course I have taken to this Data Analytics course is an Econometrics course in which we used Excel as opposed to R. 

2. Are there any components of the course about which you feel confident?

> Answer: I wish I could say yes, but, unfortunately, no. I am nervous and very excited for this course! 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am most nervous about using R and R Studio, because these softwares are unfamiliar to me and require a different way of thinking. Thankfully I have taken a coding course before, which I think should help me more quickly familiarize myself with the software. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/shivanikuckreja/Environmental_Data_Analytics_2022.git 


